[tasks.dev]
description = "Run Flutter (dev flavor)"
run = "flutter run --flavor dev -t lib/main/main_dev.dart"

[tasks.prod]
description = "Run Flutter (prod flavor)"
run = "flutter run --flavor prod -t lib/main/main_prod.dart"